# If you want to run _only_ changed tests, swap the prep line to...
# prep: go test @dirmods
# **/*.go {
# 	prep: go build
# }

**/*.go !**/*_test.go **/*.html {
	prep: go build
	daemon: ./brickrecon serve
}

**/*_test.go {
	prep: go test -short @dirmods
}